### PR TITLE
some code enhancements

### PR DESCRIPTION
**Pull request by AbdulBasit313**
1. destructure the code in some files.
2. added index.js files for default exporting the component.
3. removed unnecessary spaces.
4. structured the import statements in app.js.

Hope everything will be working as expected.
You need to show a loader when we click the searched country.

### CODE REVIEW

**Comment by Hina-softwareEngineer** [comment]
Thanks for your suggestion. Can you tell me where to show the loader when we click? Under history.push or in the country component?

**Comment by AbdulBasit313** [comment]
> Thanks for your suggestion. Can you tell me where to show the loader when we click? Under history.push or in the country component?

Why `history.push`? can't we just use react router link? it will directly link to country data page. If data will be true, it will show the data otherwise loading...

**Comment by Hina-softwareEngineer** [comment]
> Why `history.push`? can't we just use react-router link? it will directly link to the country data page. If data will be true, it will show the data otherwise loading...

I have first used `history.push`. As it takes time to show country component. Then I will replace it with Link. But there is no difference. `Link` takes the same time as `history.push` takes. So I again use `history.push` as CSS styles have been done according to `history.push`. I don't know how to improve it when user click on country name then how to load country component faster. If you can, please do it.

**Comment by AbdulBasit313** [comment]
> > Why `history.push`? can't we just use react-router link? it will directly link to the country data page. If data will be true, it will show the data otherwise loading...
> 
> I have first used `history.push`. As it takes time to show country component. Then I will replace it with Link. But there is no difference. `Link` takes the same time as `history.push` takes. So I again use `history.push` as CSS styles have been done according to `history.push`. I don't know how to improve it when user click on country name then how to load country component faster. If you can, please do it.

We need to use React suspense and lazy loading. I have tried it works first time but when I go back and research the country it behaves the same as now. One more thing, after visiting the country when we go back to home page it recalls the API? can we cache the data? Just a thought...

**Comment by Hina-softwareEngineer** [comment]
> We need to use React suspense and lazy loading. I have tried it works first time but when I go back and research the country it behaves the same as now. One more thing, after visiting the country when we go back to home page it recalls the API? can we cache the data? Just a thought...

Yes, we can cache the data and cache has to update when user refreshes. Are React Suspense and Lazy loading solves the problem that loader will be shown until country component is fully loaded on clicking country component??

**Pull request merged**
